// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'views/layout', 'controllers/head_nav_controller', 'controllers/tags_sidebar_controller', 'routes'], function(Chaplin, Layout, HeadNavController, TagsSidebarController, routes) {
  'use strict';

  var LinksApplication;
  return LinksApplication = (function(_super) {

    __extends(LinksApplication, _super);

    function LinksApplication() {
      return LinksApplication.__super__.constructor.apply(this, arguments);
    }

    LinksApplication.prototype.title = 'Chaplin Example Application';

    LinksApplication.prototype.initialize = function() {
      LinksApplication.__super__.initialize.apply(this, arguments);
      this.initDispatcher();
      this.initLayout();
      this.initMediator();
      this.initControllers();
      this.initRouter(routes);
      return typeof Object.freeze === "function" ? Object.freeze(this) : void 0;
    };

    LinksApplication.prototype.initLayout = function() {
      return this.layout = new Layout({
        title: this.title
      });
    };

    LinksApplication.prototype.initControllers = function() {
      new HeadNavController();
      return new TagsSidebarController();
    };

    LinksApplication.prototype.initMediator = function() {
      Chaplin.mediator.user = null;
      return Chaplin.mediator.seal();
    };

    return LinksApplication;

  })(Chaplin.Application);
});
