// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'text!templates/head_nav.hbs'], function(View, template) {
  'use strict';

  var HeadNavView;
  return HeadNavView = (function(_super) {

    __extends(HeadNavView, _super);

    function HeadNavView() {
      return HeadNavView.__super__.constructor.apply(this, arguments);
    }

    HeadNavView.prototype.template = template;

    template = null;

    HeadNavView.prototype.container = '#nav-head';

    HeadNavView.prototype.autoRender = true;

    HeadNavView.prototype.initialize = function() {
      HeadNavView.__super__.initialize.apply(this, arguments);
      return this.subscribeEvent('matchRoute', this.setNavBtn);
    };

    HeadNavView.prototype.setNavBtn = function(e) {
      $('ul:.nav > li').removeClass('active');
      return $(this.el).find('a[href="/' + e.pattern + '"]').parent().addClass('active');
    };

    return HeadNavView;

  })(View);
});
