// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'text!templates/link.hbs'], function(View, template) {
  'use strict';

  var LinkView;
  return LinkView = (function(_super) {

    __extends(LinkView, _super);

    function LinkView() {
      return LinkView.__super__.constructor.apply(this, arguments);
    }

    LinkView.prototype.template = template;

    template = null;

    LinkView.prototype.tagName = 'li';

    LinkView.prototype.className = 'link';

    return LinkView;

  })(View);
});
