// Generated by CoffeeScript 1.3.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'views/base/collection_view', 'views/link_view', 'text!templates/read_links.hbs'], function(Chaplin, CollectionView, LinkView, template) {
  'use strict';

  var ReadLinksView, mediator;
  mediator = Chaplin.mediator;
  return ReadLinksView = (function(_super) {

    __extends(ReadLinksView, _super);

    function ReadLinksView() {
      this.filterByCurrentTag = __bind(this.filterByCurrentTag, this);

      this.setCurrentTag = __bind(this.setCurrentTag, this);
      return ReadLinksView.__super__.constructor.apply(this, arguments);
    }

    ReadLinksView.prototype.template = template;

    template = null;

    ReadLinksView.prototype.container = '#links-section';

    /* subview related
    */


    ReadLinksView.prototype.className = 'links';

    ReadLinksView.prototype.tagName = 'div';

    ReadLinksView.prototype.id = 'link-list';

    ReadLinksView.prototype.listSelector = 'ul';

    ReadLinksView.prototype.initialize = function() {
      ReadLinksView.__super__.initialize.apply(this, arguments);
      this.subscribeEvent('startupController', this.onStartup);
      this.subscribeEvent('beforeControllerDispose', this.onDisposal);
      return this.subscribeEvent('TagsSidebarView:filterLinks', this.setCurrentTag);
    };

    ReadLinksView.prototype.getView = function(item) {
      return new LinkView({
        model: item
      });
    };

    ReadLinksView.prototype.onStartup = function(e) {
      return mediator.publish('ReadLinks:startup');
    };

    ReadLinksView.prototype.onDisposal = function(e) {
      return mediator.publish('ReadLinks:disposal');
    };

    ReadLinksView.prototype.setCurrentTag = function(tag) {
      this.current_tag = tag;
      return this.filter(this.filterByCurrentTag);
    };

    ReadLinksView.prototype.filterByCurrentTag = function(link, idx) {
      var current_tag, intersection, link_tags;
      if (this.current_tag) {
        link_tags = link.get('tags').split(",");
        current_tag = [this.current_tag];
        intersection = _.intersection(current_tag, link_tags);
        if (intersection.length > 0) {
          return link;
        } else {
          return false;
        }
      }
    };

    return ReadLinksView;

  })(CollectionView);
});
