// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'text!templates/save_links.hbs'], function(View, template) {
  'use strict';

  var SaveLinksView;
  return SaveLinksView = (function(_super) {

    __extends(SaveLinksView, _super);

    function SaveLinksView() {
      return SaveLinksView.__super__.constructor.apply(this, arguments);
    }

    SaveLinksView.prototype.template = template;

    template = null;

    SaveLinksView.prototype.className = 'sidebar';

    SaveLinksView.prototype.container = '#links-section';

    SaveLinksView.prototype.autoRender = true;

    return SaveLinksView;

  })(View);
});
