// Generated by CoffeeScript 1.3.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['tooltip', 'chaplin', 'syphon', 'views/base/view', 'models/link', 'text!templates/save_links.hbs'], function(tooltip, Chaplin, Syphon, View, Link, template) {
  'use strict';

  var SaveLinksView, mediator;
  mediator = Chaplin.mediator;
  return SaveLinksView = (function(_super) {

    __extends(SaveLinksView, _super);

    function SaveLinksView() {
      this.linkAdded = __bind(this.linkAdded, this);
      return SaveLinksView.__super__.constructor.apply(this, arguments);
    }

    SaveLinksView.prototype.template = template;

    template = null;

    SaveLinksView.prototype.className = 'sidebar';

    SaveLinksView.prototype.container = '#links-section';

    SaveLinksView.prototype.autoRender = true;

    SaveLinksView.prototype.initialize = function() {
      SaveLinksView.__super__.initialize.apply(this, arguments);
      this.subscribeEvent('TagsSidebarView:tagClicked', this.addTag);
      this.subscribeEvent('startupController', this.setupTooltips);
      return this.delegate('submit', 'form', this.saveLink);
    };

    SaveLinksView.prototype.saveLink = function(e) {
      var data, link, tag_list;
      e.preventDefault();
      $('img.loading').show();
      data = Syphon.serialize(this);
      tag_list = data.tags.replace(/^\s+|\s+$/g, "").split(",");
      link = new Link({
        url: data.url,
        tags: tag_list
      });
      mediator.publish('tags:add', tag_list);
      this.collection.add(link);
      return link.save().done(this.linkAdded);
    };

    SaveLinksView.prototype.linkAdded = function(item, collection, options) {
      if (options == null) {
        options = {};
      }
      return mediator.publish('!router:route', 'links');
    };

    SaveLinksView.prototype.addTag = function(tag_name) {
      var content, inp;
      inp = $('input[name=tags]');
      content = inp.val() + "," + tag_name;
      return inp.val(content.replace(/(^,)|(,$)/g, ""));
    };

    SaveLinksView.prototype.setupTooltips = function(e) {
      return $(this.el).find('input').tooltip();
    };

    return SaveLinksView;

  })(View);
});
