// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'views/tags_sidebar_view_base', 'views/tag_view', 'models/tag', 'text!templates/tags_sidebar.hbs'], function(Chaplin, TagsSidebarViewBase, TagView, Tag, template) {
  'use strict';

  var TagsSidebarView, mediator;
  mediator = Chaplin.mediator;
  return TagsSidebarView = (function(_super) {

    __extends(TagsSidebarView, _super);

    function TagsSidebarView() {
      return TagsSidebarView.__super__.constructor.apply(this, arguments);
    }

    return TagsSidebarView;

  })(TagsSidebarViewBase);
});
