// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'text!templates/tags_sidebar.hbs'], function(View, template) {
  'use strict';

  var TagsSidebarView;
  return TagsSidebarView = (function(_super) {

    __extends(TagsSidebarView, _super);

    function TagsSidebarView() {
      return TagsSidebarView.__super__.constructor.apply(this, arguments);
    }

    TagsSidebarView.prototype.template = template;

    template = null;

    TagsSidebarView.prototype.className = 'sidebar';

    TagsSidebarView.prototype.container = '#tags-section';

    TagsSidebarView.prototype.autoRender = true;

    return TagsSidebarView;

  })(View);
});
