// Generated by CoffeeScript 1.3.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/collection', 'models/link'], function(Chaplin, Collection, Link) {
  'use strict';

  var Links, mediator;
  mediator = Chaplin.mediator;
  return Links = (function(_super) {

    __extends(Links, _super);

    function Links() {
      this.rs = __bind(this.rs, this);
      return Links.__super__.constructor.apply(this, arguments);
    }

    Links.prototype.model = Link;

    Links.prototype.url = '/api/links';

    Links.prototype.defaults = {
      message: 'This is a link collection!'
    };

    Links.prototype.initialize = function(attributes, options) {
      Links.__super__.initialize.apply(this, arguments);
      this.subscribeEvent('TagsSidebarView:filterLinks', this.rs);
      this.initSyncMachine();
      return this.fetch();
    };

    Links.prototype.filterByTag = function(tag) {
      return this.filter(function(link) {
        var in_tags, intersection, l, link_tags, out_tags;
        link_tags = link.get('tags');
        in_tags = [tag];
        out_tags = link_tags.split(",");
        intersection = _.intersection(in_tags, out_tags);
        return l = intersection.length > 0 ? link : false;
      });
    };

    Links.prototype.rs = function(tag) {
      var filtered;
      filtered = this.filterByTag(tag);
      mediator.publish('Links:filterd', filtered);
      return console.log(filtered);
    };

    return Links;

  })(Collection);
});
