// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/collection', 'models/link'], function(Chaplin, Collection, Link) {
  'use strict';

  var Links, mediator;
  mediator = Chaplin.mediator;
  return Links = (function(_super) {

    __extends(Links, _super);

    function Links() {
      return Links.__super__.constructor.apply(this, arguments);
    }

    Links.prototype.model = Link;

    Links.prototype.url = '/api/links';

    Links.prototype.defaults = {
      message: 'This is a link collection!'
    };

    Links.prototype.initialize = function(attributes, options) {
      Links.__super__.initialize.apply(this, arguments);
      this.initSyncMachine();
      return this.fetch();
    };

    return Links;

  })(Collection);
});
