// Generated by CoffeeScript 1.3.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/collection', 'models/tag'], function(Chaplin, Collection, Tag) {
  'use strict';

  var Tags;
  return Tags = (function(_super) {

    __extends(Tags, _super);

    function Tags() {
      this.go = __bind(this.go, this);
      return Tags.__super__.constructor.apply(this, arguments);
    }

    Tags.prototype.model = Tag;

    Tags.prototype.url = '/api/tags';

    Tags.prototype.defaults = {
      message: 'This is a tag collection!'
    };

    Tags.prototype.initialize = function(attributes, options) {
      Tags.__super__.initialize.apply(this, arguments);
      this.initSyncMachine();
      this.beginSync();
      return this.fetch().done(this.go);
    };

    Tags.prototype.go = function() {
      return this.finishSync();
    };

    return Tags;

  })(Collection);
});
