// Generated by CoffeeScript 1.4.0

define(['handlebars', 'chaplin', 'lib/utils'], function(Handlebars, Chaplin, utils) {
  'use strict';

  var mediator;
  mediator = Chaplin.mediator;
  return null;
});
