// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'views/head_nav_view'], function(Chaplin, HeadNavView) {
  'use strict';

  var HeadNavController;
  return HeadNavController = (function(_super) {

    __extends(HeadNavController, _super);

    function HeadNavController() {
      return HeadNavController.__super__.constructor.apply(this, arguments);
    }

    HeadNavController.prototype.title = 'savemylinks nav';

    HeadNavController.prototype.initialize = function() {
      return this.show();
    };

    HeadNavController.prototype.historyURL = function(params) {
      return '';
    };

    HeadNavController.prototype.show = function(params) {
      return this.view = new HeadNavView();
    };

    return HeadNavController;

  })(Chaplin.Controller);
});
