// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/link', 'models/links', 'views/save_links_view', 'views/read_links_view'], function(Chaplin, Link, Links, SaveLinksView, readLinksView) {
  'use strict';

  var LinksController;
  return LinksController = (function(_super) {

    __extends(LinksController, _super);

    function LinksController() {
      return LinksController.__super__.constructor.apply(this, arguments);
    }

    LinksController.prototype.title = 'bookmarks application';

    LinksController.prototype.initialize = function() {
      return this.collection = new Links();
    };

    LinksController.prototype.historyURL = function(params) {
      return '';
    };

    LinksController.prototype.save = function(params) {
      return this.view = new SaveLinksView({
        collection: this.collection
      });
    };

    LinksController.prototype.read = function(params) {
      return this.view = new ReadLinksView({
        collection: this.collection
      });
    };

    return LinksController;

  })(Chaplin.Controller);
});
