// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/link', 'views/read_links_view'], function(Chaplin, Link, ReadLinksView) {
  'use strict';

  var ReadLinksController;
  return ReadLinksController = (function(_super) {

    __extends(ReadLinksController, _super);

    function ReadLinksController() {
      return ReadLinksController.__super__.constructor.apply(this, arguments);
    }

    ReadLinksController.prototype.title = 'Read links';

    ReadLinksController.prototype.historyURL = function(params) {
      return '';
    };

    ReadLinksController.prototype.show = function(params) {
      console.debug('ReadLinksController#show');
      this.model = new Link();
      return this.view = new ReadLinksView({
        model: this.model
      });
    };

    return ReadLinksController;

  })(Chaplin.Controller);
});
