// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/link', 'views/save_links_view'], function(Chaplin, Link, SaveLinksView) {
  'use strict';

  var SaveLinksController;
  return SaveLinksController = (function(_super) {

    __extends(SaveLinksController, _super);

    function SaveLinksController() {
      return SaveLinksController.__super__.constructor.apply(this, arguments);
    }

    SaveLinksController.prototype.title = 'Save links';

    SaveLinksController.prototype.historyURL = function(params) {
      return '';
    };

    SaveLinksController.prototype.show = function(params) {
      console.debug('SaveLinksController#show');
      this.model = new Link();
      return this.view = new SaveLinksView({
        model: this.model
      });
    };

    return SaveLinksController;

  })(Chaplin.Controller);
});
