// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/link', 'models/links', 'views/save_links_view'], function(Chaplin, Link, Links, SaveLinksView) {
  'use strict';

  var SaveLinksController;
  return SaveLinksController = (function(_super) {

    __extends(SaveLinksController, _super);

    function SaveLinksController() {
      return SaveLinksController.__super__.constructor.apply(this, arguments);
    }

    SaveLinksController.prototype.title = 'Save bookmark';

    SaveLinksController.prototype.initialize = function() {
      return this.collection = new Links();
    };

    SaveLinksController.prototype.historyURL = function(params) {
      return '';
    };

    SaveLinksController.prototype.show = function(params) {
      return this.view = new SaveLinksView({
        collection: this.collection
      });
    };

    return SaveLinksController;

  })(Chaplin.Controller);
});
