// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/tags', 'views/tags_sidebar_view_esit', 'views/tags_sidebar_view_save'], function(Chaplin, Tags, TagsSidebarViewEdit, TagsSidebarViewSave) {
  'use strict';

  var tagsController;
  return tagsController = (function(_super) {

    __extends(tagsController, _super);

    function tagsController() {
      return tagsController.__super__.constructor.apply(this, arguments);
    }

    tagsController.prototype.title = 'Tags sidebar';

    tagsController.prototype.initialize = function() {
      return this.collection = new Tags();
    };

    tagsController.prototype.historyURL = function(params) {
      return '';
    };

    tagsController.prototype.read = function(params) {
      console.debug('TagsSidebarController#show');
      return this.view = new TagsSidebarViewRead({
        collection: this.collection
      });
    };

    tagsController.prototype.save = function(params) {
      console.debug('TagsSidebarController#edit');
      return this.view = new TagsSidebarViewEdit({
        collection: this.collection
      });
    };

    return tagsController;

  })(Chaplin.Controller);
});
