// Generated by CoffeeScript 1.3.3

define(function() {
  'use strict';
  return function(match) {
    match('', 'links#save');
    match('read-links', 'links#read');
    match('', 'tags#save');
    return match('read-links', 'tags#read');
  };
});
