// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/tag', 'views/tags_sidebar_view'], function(Chaplin, Tag, TagsSidebarView) {
  'use strict';

  var TagsSidebarController;
  return TagsSidebarController = (function(_super) {

    __extends(TagsSidebarController, _super);

    function TagsSidebarController() {
      return TagsSidebarController.__super__.constructor.apply(this, arguments);
    }

    TagsSidebarController.prototype.title = 'Tags sidebar';

    TagsSidebarController.prototype.initialize = function() {
      return this.show();
    };

    TagsSidebarController.prototype.historyURL = function(params) {
      return '';
    };

    TagsSidebarController.prototype.show = function(params) {
      this.model = new Tag();
      return this.view = new TagsSidebarView({
        model: this.model
      });
    };

    return TagsSidebarController;

  })(Chaplin.Controller);
});
